# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001
@AuthCookieName = .AspNetCore.Identity.Application
@AuthCookieValue = <AuthCookieValue>

# GET Identity Account Login
# Get the @RequestVerificationToken necessary for logging in.
GET {{Web_HostAddress}}/Identity/Account/Login

###

# POST Identity Account Login
# Get the @AuthCookieValue necessary for authenticating requests.
@Email=administrator@localhost
@Password=Administrator1!
@RequestVerificationToken=<RequestVerificationToken>
POST {{Web_HostAddress}}/Identity/Account/Login
Content-Type: application/x-www-form-urlencoded

Input.Email={{Email}}&Input.Password={{Password}}&__RequestVerificationToken={{RequestVerificationToken}}

###

# GET Sports
GET {{Web_HostAddress}}/api/sports
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

# POST Sports
POST {{Web_HostAddress}}/api/sports
Cookie: {{AuthCookieName}}={{AuthCookieValue}}
Content-Type: application/json

{
  "SportName": "Football",
  "Description": "Association football"
}

###

# GET Fields
GET {{Web_HostAddress}}/api/fields
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

# POST Fields
POST {{Web_HostAddress}}/api/fields
Cookie: {{AuthCookieName}}={{AuthCookieValue}}
Content-Type: application/json

{
  "SportId": 1,
  "FieldName": "Field A",
  "Location": "Main Stadium",
  "Capacity": 22,
  "Description": "Main football field"
}

###

# GET Bookings
GET {{Web_HostAddress}}/api/bookings
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

# POST Bookings
POST {{Web_HostAddress}}/api/bookings
Cookie: {{AuthCookieName}}={{AuthCookieValue}}
Content-Type: application/json

{
  "CustomerId": 1,
  "FieldId": 1,
  "SportId": 1,
  "BookingDate": "2024-12-25",
  "StartTime": "10:00:00",
  "EndTime": "12:00:00",
  "TotalPrice": 100.00
}

###

# GET Users
GET {{Web_HostAddress}}/api/users
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

# GET Pricing
GET {{Web_HostAddress}}/api/pricing
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###